# Generated by Django 5.2.8 on 2026-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_company', models.CharField(max_length=100, verbose_name='입력 회사명')),
                ('matched_company', models.CharField(max_length=100, verbose_name='실제 종목명')),
                ('stock_code', models.CharField(max_length=30, verbose_name='종목 코드')),
                ('raw_comments', models.JSONField(default=list, verbose_name='원본 댓글 목록')),
                ('cleaned_comments', models.JSONField(default=list, verbose_name='정제 댓글 목록')),
                ('augmented_comments', models.JSONField(default=list, verbose_name='증강 댓글 목록')),
                ('integrated_data', models.JSONField(default=dict, verbose_name='통합 결과')),
                ('iqr_info', models.JSONField(default=dict, verbose_name='IQR 임계값 정보')),
                ('summary', models.TextField(blank=True, verbose_name='댓글 요약')),
                ('status_message', models.TextField(blank=True, verbose_name='처리 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
