# Generated by Django 5.2.13 on 2026-04-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_company_name', models.CharField(max_length=100)),
                ('original_comments', models.JSONField(default=list)),
                ('cleaned_comments', models.JSONField(default=list)),
                ('augmented_comments', models.JSONField(default=list)),
                ('iqr_threshold', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
